name: Binance Collector

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  collect:
    runs-on: ubuntu-latest
    env:
      OUT_DIR: data
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        env:
          TZ: Asia/Seoul
        run: |
          python collector.py

      - name: Commit and push results
        env:
          TZ: Asia/Seoul
        run: |
          if git status --short | grep -qE '^(M| M|\?\?)'; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            timestamp=$(date '+%Y-%m-%d %H:%M')
            git add ${OUT_DIR:-data}
            git commit -m "update: data (KST ${timestamp})"
            git push
          else
            echo "No changes to commit."
          fi
